# config/s3.yml
development:
  access_key_id: AKIAIEGXXU5PX3RHDSQQ
  secret_code: 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

production:
  access_key_id: AKIAI26U7S6APDZX3I2Q
  secret_code: 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
